/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package com.camile.checker.language;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static com.camile.checker.FlinkSqlCheckerTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>_FlinkSqlCheckerLexer.flex</tt>
 */
public class _FlinkSqlCheckerLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [10, 5, 6]
   * Total runtime size is 3200 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>11]<<5)|((ch>>6)&0x1f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 544 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\1\1\3\1\1\1\4\2\1\1\5\11\6\1\7\13\1\1\10\u0200\1");

  /* The ZZ_CMAP_Y table has 288 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\13\3\1\4\113\3\1\5\5\3\1\6\1\7\36\3\1\10\67\3\106\11\1\12\35"+
    "\3\1\13\3\3");

  /* The ZZ_CMAP_A table has 768 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\2\4\1\22\0\1\2\1\27\1\5\4\0\1\4\1\7\1\10\1\23\1\20\1\17\1\3\1\21\1"+
    "\31\12\14\1\22\1\30\1\25\1\24\1\26\2\0\1\41\2\11\1\44\1\37\1\47\1\42\1\11"+
    "\1\46\4\11\1\43\1\50\3\11\1\51\1\36\3\11\1\40\2\11\1\32\1\6\1\33\1\0\1\16"+
    "\1\0\32\11\1\34\1\15\1\35\7\0\1\1\32\0\1\2\224\0\1\45\12\0\1\2\77\0\13\2\35"+
    "\0\2\1\5\0\1\2\57\0\1\2\40\0\1\2\1\13\76\0\146\12\46\0\1\12\15\0\1\12\45\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\2\1\6\1\7"+
    "\1\1\2\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\2\2\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\3\1\1\31\1\1\1\32\2\0"+
    "\1\33\1\0\1\34\1\35\1\36\1\37\4\1\1\40"+
    "\1\41\2\1\1\42\1\43\3\1\1\44\1\1\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\52\0\52"+
    "\0\374\0\52\0\u0126\0\u0150\0\u017a\0\52\0\52\0\52"+
    "\0\u017a\0\52\0\52\0\52\0\u01a4\0\u01ce\0\u01f8\0\52"+
    "\0\52\0\52\0\52\0\52\0\52\0\u0222\0\u024c\0\u0276"+
    "\0\52\0\u02a0\0\u02ca\0\u02f4\0\322\0\52\0\u031e\0\52"+
    "\0\52\0\52\0\52\0\u0348\0\u0372\0\u039c\0\u03c6\0\374"+
    "\0\52\0\u03f0\0\u041a\0\374\0\374\0\u0444\0\u046e\0\u0498"+
    "\0\374\0\u04c2\0\374";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\3\11"+
    "\1\40\1\11\1\41\1\42\3\11\53\0\2\3\52\0"+
    "\1\43\46\0\1\44\1\0\50\44\5\45\1\46\1\47"+
    "\43\45\11\0\1\11\24\0\7\11\1\0\4\11\13\0"+
    "\1\13\52\0\1\14\1\15\3\0\1\15\44\0\2\15"+
    "\3\0\1\15\54\0\1\50\1\0\1\51\47\0\1\52"+
    "\51\0\1\53\36\0\1\11\24\0\1\11\1\54\5\11"+
    "\1\0\4\11\11\0\1\11\24\0\2\11\1\55\2\11"+
    "\1\56\1\11\1\0\4\11\11\0\1\11\24\0\7\11"+
    "\1\0\2\11\1\57\1\11\11\0\1\11\24\0\7\11"+
    "\1\0\1\11\1\60\2\11\1\43\1\0\50\43\4\0"+
    "\1\61\45\0\1\45\1\0\50\45\11\0\1\11\24\0"+
    "\2\11\1\62\4\11\1\0\4\11\11\0\1\11\24\0"+
    "\7\11\1\0\3\11\1\63\11\0\1\11\24\0\6\11"+
    "\1\64\1\0\4\11\11\0\1\11\24\0\1\65\6\11"+
    "\1\0\4\11\11\0\1\11\24\0\1\66\6\11\1\0"+
    "\4\11\11\0\1\11\24\0\7\11\1\0\1\67\3\11"+
    "\11\0\1\11\24\0\3\11\1\70\3\11\1\0\4\11"+
    "\11\0\1\11\24\0\1\71\6\11\1\0\4\11\11\0"+
    "\1\11\24\0\4\11\1\72\2\11\1\0\4\11\11\0"+
    "\1\11\24\0\4\11\1\73\2\11\1\0\4\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1260];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\2\11\1\1\1\11\3\1\3\11"+
    "\1\1\3\11\3\1\6\11\3\1\1\11\2\1\2\0"+
    "\1\11\1\0\4\11\5\1\1\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[59];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _FlinkSqlCheckerLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _FlinkSqlCheckerLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ENGLISH_STRING;
            } 
            // fall through
          case 38: break;
          case 2: 
            { return BAD_CHARACTER;
            } 
            // fall through
          case 39: break;
          case 3: 
            { return WHITE_SPACE;
            } 
            // fall through
          case 40: break;
          case 4: 
            { return HYPHEN;
            } 
            // fall through
          case 41: break;
          case 5: 
            { return SINGLE_QUOTATION;
            } 
            // fall through
          case 42: break;
          case 6: 
            { return LEFT_BRACKET;
            } 
            // fall through
          case 43: break;
          case 7: 
            { return RIGHT_BRACKET;
            } 
            // fall through
          case 44: break;
          case 8: 
            { return CHINESE_STRING;
            } 
            // fall through
          case 45: break;
          case 9: 
            { return NUMBER;
            } 
            // fall through
          case 46: break;
          case 10: 
            { return DOUBLE;
            } 
            // fall through
          case 47: break;
          case 11: 
            { return UNDERSCORE;
            } 
            // fall through
          case 48: break;
          case 12: 
            { return COMMA;
            } 
            // fall through
          case 49: break;
          case 13: 
            { return PLUS;
            } 
            // fall through
          case 50: break;
          case 14: 
            { return PERIOD;
            } 
            // fall through
          case 51: break;
          case 15: 
            { return COLON;
            } 
            // fall through
          case 52: break;
          case 16: 
            { return ANY;
            } 
            // fall through
          case 53: break;
          case 17: 
            { return EQUALS;
            } 
            // fall through
          case 54: break;
          case 18: 
            { return LT;
            } 
            // fall through
          case 55: break;
          case 19: 
            { return SEMI_COLON;
            } 
            // fall through
          case 56: break;
          case 20: 
            { return SLASH;
            } 
            // fall through
          case 57: break;
          case 21: 
            { return LSBTRACE;
            } 
            // fall through
          case 58: break;
          case 22: 
            { return RSBTRACE;
            } 
            // fall through
          case 59: break;
          case 23: 
            { return LBRACE;
            } 
            // fall through
          case 60: break;
          case 24: 
            { return RBRACE;
            } 
            // fall through
          case 61: break;
          case 25: 
            { return Ε;
            } 
            // fall through
          case 62: break;
          case 26: 
            { return COMMENT;
            } 
            // fall through
          case 63: break;
          case 27: 
            { return STRINGLIT;
            } 
            // fall through
          case 64: break;
          case 28: 
            { return LE;
            } 
            // fall through
          case 65: break;
          case 29: 
            { return NOT_EQUALS;
            } 
            // fall through
          case 66: break;
          case 30: 
            { return GE;
            } 
            // fall through
          case 67: break;
          case 31: 
            { return NOT_EQUALS2;
            } 
            // fall through
          case 68: break;
          case 32: 
            { return IF;
            } 
            // fall through
          case 69: break;
          case 33: 
            { return CHARACTER;
            } 
            // fall through
          case 70: break;
          case 34: 
            { return END;
            } 
            // fall through
          case 71: break;
          case 35: 
            { return NOT;
            } 
            // fall through
          case 72: break;
          case 36: 
            { return EXSIT;
            } 
            // fall through
          case 73: break;
          case 37: 
            { return TEXTAGG;
            } 
            // fall through
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
